import cv2


class TrackerParams:
    MARGIN_FRACTION = 1 / 5
    CANNY_THRESHOLD_1 = 50
    CANNY_THRESHOLD_2 = 150
    MIN_LINE_LENGTH = 50
    MAX_LINE_GAP = 30
    THRESHOLD_HOUGH_LINES_P = 50
    APERTURE_SIZE = 3
    PNP_FLAG = cv2.SOLVEPNP_ITERATIVE

    MAX_NUMBER_LINES_PHI_RO = 20  # 20
    MAX_DIFF_PHI = 0.015  # 0.1
    MAX_DIFF_RO = 10
    MAX_DIFF_PNP = 3.7
    PHI_SCORE_COEFF = 400


class TrackerState:
    pass
