from .ground_truth_candidate import GroundTruthCandidate
from .pnp_rmse_candidate import PNPrmseCandidate
from .previous_pos_candidate import PreviousPoseCandidate
from .rect_candidate import RectCandidate
from .square_candidate import SquareCandidate
from .gradient_candidate import RectangleGradientCandidate
from .outer_variance_candidate import OuterVarianceCandidate
# TODO: outer variance
# TODO: aspect ratio
# TODO: corners eigenvalues
